
Declare Global NONE to "NONE".

Declare Global VESSEL_TYPES to List().
Declare Global VESSEL_TYPE_STARSHIP to "STARSHIP". 
    VESSEL_TYPES:ADD(VESSEL_TYPE_STARSHIP).
Declare Global VESSEL_TYPE_SUPER_HEAVY_BOOSTER to "SUPER_HEAVY_BOOSTER".
    VESSEL_TYPES:ADD(VESSEL_TYPE_SUPER_HEAVY_BOOSTER).
Declare Global VESSEL_TYPE_FALCON_UPPER_STAGE to "FALCON_9_UPPER_STAGE".
    VESSEL_TYPES:ADD(VESSEL_TYPE_FALCON_UPPER_STAGE).
Declare Global VESSEL_TYPE_FALCON_BOOSTER to "FALCON_9_BOOSTER".
    VESSEL_TYPES:ADD(VESSEL_TYPE_FALCON_BOOSTER).
Declare Global VESSEL_TYPE_FALCON_9 TO "FALCON_9_ASSEMBLY".
    VESSEL_TYPES:Add(VESSEL_TYPE_FALCON_9).
// TODO: falcon 9 cargo/crew/fairing
Declare Global VESSEL_TYPE_FALCON_HEAVY TO "FALCON_HEAVY".
    VESSEL_TYPES:Add(VESSEL_TYPE_FALCON_HEAVY).
    
Declare Global VESSEL_TYPE_NEWGLENN to "NEWGLENN". 
    VESSEL_TYPES:ADD(VESSEL_TYPE_NEWGLENN).
Declare Global VESSEL_TYPE_ELECTRON to "ELECTRON". 
    VESSEL_TYPES:ADD(VESSEL_TYPE_ELECTRON).


Declare Global RESOURCE_LH2 to "LqdHydrogen".
Declare Global RESOURCE_LIQUID_FUEL to "LiquidFuel".
Declare Global RESOURCE_LIQUID_METHANE to "LqdMethane".
Declare Global RESOURCE_OXIDIZER to "Oxidizer".

Declare Global AVIONICS_CPU_ASSIGN to "AVIONICS_CPU_ASSIGN".
Declare Global AVIONICS_CPU_RUN to "AVIONICS_CPU_RUN".
Declare Global AVIONICS_CPU_STOP to "AVIONICS_CPU_STOP".

Global ACTIVE_FALCON_BOOSTER_VESSEL_NAME TO "ACTIVE_FALCON_BOOSTER_".
Global SIDE_BOOSTER_LANDING_INIT_MESSAGE to "INIT_BOOSTER_LANDING".
Global CORE_BOOSTER_AVIONICS_CPU_NAME TO "AVIONICS_CPU_CORE_BOOSTER".
Global CORE_BOOSTER_CPU_NAME TO "CPU_BOOSTER_CORE".
Global RIGHT_BOOSTER_CPU_NAME TO "CPU_RIGHT_BOOSTER".
Global RIGHT_BOOSTER_AVIONICS_CPU_NAME TO "AVIONICS_CPU_RIGHT_BOOSTER".
Global LEFT_BOOSTER_CPU_NAME TO "CPU_LEFT_BOOSTER".
Global LEFT_BOOSTER_AVIONICS_CPU_NAME TO "AVIONICS_CPU_LEFT_BOOSTER".
Global TWIN_BOOSTER_ALIGNMENT_MESSAGE TO "TWIN_BOOSTER_ALIGNMENT".

Global KEY_BOOSTERSIDE TO "boosterside".
Global KEY_EXPEND_OPTION TO "EXPEND_OPTION"..
Global KEY_LAUNCH_HEADING TO "LAUNCH_HEADING".
Global KEY_PAYLOAD_MASS TO "PAYLOAD_MASS".
Global KEY_VESSEL_TYPE TO "VESSEL_TYPE_INDICATOR".

Global INDICATOR_BOOSTER_CORE TO "CORE". 
Global INDICATOR_BOOSTER_LEFT TO "LEFT".
Global INDICATOR_BOOSTER_RIGHT TO "RIGHT".

Global ACTIVE_FALCON_UPPER_VESSEL_NAME TO "ACTIVE_FALCON_UPPER". 
Global FALCON_DECOUPLER_UPPERSTAGE TO "DECOUPLER_UPPERSTAGE".
Global FALCON_UPPERSTAGE_CPU_NAME TO "CPU_UPPERSTAGE".
Global FALCON_ENG_UPPERSTAGE TO "UPPER_MER_VAC".
Global FALCON_UPPERSTAGE_HANDOFF TO "FALCON_UPPERSTAGE_HANDOFF".

Global ENGINES_MERLIN_9 TO "MERLIN_9".
Global ENGINES_MERLIN_9_CORE TO "MERLIN_9_CORE".

Global BOOSTER_EXPEND_SIGNAL to "EXPEND_SALUTE".
Global BOOSTER_PRESERVE_SIGNAL TO "BOOSTER_PRESERVE".

// Global PERFORMANCE_FALCON_HEAVY_MAX_PAYLOAD TO 28.
