Global ACTIVE_FALCON_BOOSTER_VESSEL_NAME TO "ACTIVE_FALCON_BOOSTER_".
Global SIDE_BOOSTER_LANDING_INIT_MESSAGE to "INIT_BOOSTER_LANDING".
Global RIGHT_BOOSTER_CPU_NAME TO "CPU_RIGHT_BOOSTER".
Global LEFT_BOOSTER_CPU_NAME TO "CPU_LEFT_BOOSTER".
